-- Your SQL goes here
CREATE TABLE "device" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "device__name" TEXT NOT NULL,
    "device__contact" TEXT NOT NULL,
    "device__location" TEXT NOT NULL,
    "device__serialno" TEXT NOT NULL,
    "network__macaddr" TEXT NOT NULL,
    "network__ip" TEXT NOT NULL,
    "network__netmask" TEXT NOT NULL,
    "network__dns" TEXT NOT NULL,
    "network__gateway" TEXT NOT NULL,
    "relais__r1" BOOLEAN NOT NULL,
    "relais__r0" BOOLEAN NOT NULL,
    "time__time" TEXT NOT NULL,
    "time__offset" TEXT NOT NULL,
    "time__invalid" BOOLEAN NOT NULL,
    "time__stamp" INTEGER NOT NULL,
    "version__filesystem" TEXT NOT NULL,
    "version__hwdesc" TEXT NOT NULL,
    "version__software" TEXT NOT NULL,
    "version__flavor" TEXT NOT NULL,
    "version__hash" TEXT NOT NULL,
    "version__branch" TEXT NOT NULL,
    "version__firmware" TEXT NOT NULL,
    "version__build" TEXT NOT NULL,
    "version__date" TEXT NOT NULL,
    "version__hardware" TEXT NOT NULL,
    "external__s2" BOOLEAN NOT NULL,
    "external__s1" BOOLEAN NOT NULL,
    "sensor__lock" BOOLEAN NOT NULL,
    "sensor__handle" BOOLEAN NOT NULL,
    "sensor__motor" BOOLEAN NOT NULL
);
